apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: vote-cluster
  region: us-east-1
  version: "1.20"
nodeGroups:
  - name: app
    minSize: 2
    maxSize: 2
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t2.medium"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
  - name: tools
    minSize: 2
    maxSize: 2
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t2.medium"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
    labels: {"tools": "true"}
    taints:
      - key: tools
        value: "true"
        effect: NoSchedule
availabilityZones: ['us-east-1a','us-east-1b']
