apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cluster
  region: us-east-1
  version: "1.21"
nodegroups:
  - name: app
    minSize: 2
    maxSize: 2
    spot: true
  - name: tools
    minSize: 2
    maxSize: 2
    instanceDistribution:
      maxPrice: 0.017
      instanceType: ["t2.medium"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
    labels: {tools: "true"}
    taints:
      - key: tools
        value: "true"
        effect: NoSchedule
